// solometro - 駅データ（自動生成・編集はこのファイルのみ）
window.LS={
  "銀座線":{bg:"#FAC775",text:"#633806"},
  "丸ノ内線":{bg:"#F09595",text:"#501313"},
  "日比谷線":{bg:"#9FE1CB",text:"#04342C"},
  "東西線":{bg:"#85B7EB",text:"#042C53"},
  "千代田線":{bg:"#C0DD97",text:"#173404"},
  "有楽町線":{bg:"#FAC775",text:"#412402"},
  "半蔵門線":{bg:"#CECBF6",text:"#26215C"},
  "南北線":{bg:"#5DCAA5",text:"#04342C"},
  "副都心線":{bg:"#D3D1C7",text:"#2C2C2A"},
  "都営浅草線":{bg:"#F5C4B3",text:"#4A1B0C"},
  "都営三田線":{bg:"#B5D4F4",text:"#042C53"},
  "都営新宿線":{bg:"#C0DD97",text:"#173404"},
  "都営大江戸線":{bg:"#F4C0D1",text:"#4B1528"},
};

window.STATIONS=[
  {id:1,stationName:"表参道",smoothMetroUrl:"https://www.smoothmetro.jp/station/omote-sando.html",
   surfaceElevator:{description:"A3出口付近（青山通り沿い）/ A4・A5出口にもEV",mapQuery:"表参道駅 A3出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:true,nearElevatorCar:"6号車",safeDoors:["6号車1番扉","1号車3番扉"],details:"【単独乗降OK】6号車1番扉（および１号車3番扉）は、スロープなしで自力で乗降できる目安値をクリアしています。さらに6号車はホームのエレベーターの目の前に着くため移動が最短です。※もし混雑などで不安があり、駅員さんにスロープを依頼したい場合も、この『EVが目の前にある6号車』から声をかけるのが一番スムーズです。"},
     {line:"千代田線",canBoardIndependently:false,details:"目安値を満たさない乗降口が大半のため、必ず駅員の手配が必要。"},
     {line:"半蔵門線",canBoardIndependently:false,details:"目安値を満たさない乗降口が大半のため、必ず駅員の手配が必要。"},
   ]},
  {id:2,stationName:"渋谷",smoothMetroUrl:"https://www.smoothmetro.jp/station/shibuya.html",
   surfaceElevator:{description:"ハチ公口側・東急スクランブルスクエア低層棟経由EV（地上直結）",mapQuery:"渋谷駅 エレベーター ハチ公口"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:true,nearElevatorCar:"6号車",safeDoors:["6号車1番扉","1号車3番扉"],details:"【単独乗降OK】6号車1番扉（および１号車3番扉）は、スロープなしで自力で乗降できる目安値をクリアしています。さらに6号車はホームのエレベーターの目の前に着くため移動が最短です。※もし混雑などで不安があり、駅員さんにスロープを依頼したい場合も、この『EVが目の前にある6号車』から声をかけるのが一番スムーズです。"},
     {line:"半蔵門線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"副都心線",canBoardIndependently:false,details:"目安値を満たさない乗降口が多いため、必ず駅員の手配が必要。"},
   ]},
  {id:3,stationName:"銀座",smoothMetroUrl:"https://www.smoothmetro.jp/station/ginza.html",
   surfaceElevator:{description:"A13出口（銀座4丁目交差点・中央通り沿い）",mapQuery:"銀座駅 A13出口 エレベーター"},
   hasWheelchairToilet:false,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:false,details:"ホームと車両の段差・隙間が目安値を超えるため、必ず駅員の手配が必要。"},
     {line:"丸ノ内線",canBoardIndependently:false,details:"ホームと車両の段差・隙間が目安値を超えるため、必ず駅員の手配が必要。"},
     {line:"日比谷線",canBoardIndependently:false,details:"ホームと車両の段差・隙間が目安値を超えるため、必ず駅員の手配が必要。"},
   ]},
  {id:4,stationName:"赤坂見附",smoothMetroUrl:"https://www.smoothmetro.jp/station/akasaka-mitsuke.html",
   surfaceElevator:{description:"外堀通り沿い エレベーター専用口（山王下方面改札直結）。※赤坂見附交差点の南側、ビックカメラ（旧赤坂東急プラザ）の向かい側",mapQuery:"赤坂見附駅 エレベーター専用出入口"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:false,details:"全車両・全ドアで段差・隙間が基準未達。乗車には駅員の手配が必要。"},
     {line:"丸ノ内線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","5号車3番扉"],details:"【単独乗降OK】全車いすスペース車両で目安値クリア。2号車3番扉・5号車3番扉が単独乗降の最適位置（2号車がEV近接）。"},
   ]},
  {id:5,stationName:"上野",smoothMetroUrl:"https://www.smoothmetro.jp/station/ueno.html",
   surfaceElevator:{description:"6番出口（上野公園・公園口方面）",mapQuery:"上野駅 6番出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:true,nearElevatorCar:"6号車",safeDoors:["6号車1番扉","1号車3番扉"],details:"【単独乗降OK】6号車1番扉（および１号車3番扉）は、スロープなしで自力で乗降できる目安値をクリアしています。さらに6号車はホームのエレベーターの目の前に着くため移動が最短です。※もし混雑などで不安があり、駅員さんにスロープを依頼したい場合も、この『EVが目の前にある6号車』から声をかけるのが一番スムーズです。"},
     {line:"日比谷線",canBoardIndependently:false,details:"目安値未達のため、必ず駅員の手配が必要。"},
   ]},
  {id:6,stationName:"池袋",smoothMetroUrl:"https://www.smoothmetro.jp/station/ikebukuro.html",
   surfaceElevator:{description:"南口・C3出口(東武百貨店前)",mapQuery:"池袋駅 C3出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"丸ノ内線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","5号車3番扉"],details:"【単独乗降OK】全車いすスペース車両で目安値クリア。2号車3番扉・5号車3番扉が単独乗降の最適位置（2号車がEV近接）。"},
     {line:"有楽町線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車4番扉","9号車1番扉"],details:"【単独乗降OK】2号車4番扉・9号車1番扉が単独乗降の最適位置。2号車がEV近接。"},
     {line:"副都心線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","9号車2番扉"],details:"【単独乗降OK】2号車3番扉・9号車2番扉が単独乗降の最適位置。2号車がEV近接。"},
   ]},
  {id:7,stationName:"飯田橋",smoothMetroUrl:"https://www.smoothmetro.jp/station/iidabashi.html",
   surfaceElevator:{description:"A1出口（外堀通り沿い・神楽坂方面）",mapQuery:"飯田橋駅 A1出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"東西線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"南北線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"有楽町線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車4番扉","9号車1番扉"],details:"【単独乗降OK】2号車4番扉・9号車1番扉が単独乗降の最適位置。2号車がEV近接。"},
     {line:"都営大江戸線",canBoardIndependently:true,nearElevatorCar:"4号車",safeDoors:["4号車2番扉"],details:"【単独乗降OK】4号車2番扉が単独乗降の最適位置。"},
   ]},
  {id:8,stationName:"大手町",smoothMetroUrl:"https://www.smoothmetro.jp/station/otemachi.html",
   surfaceElevator:{description:"C3b出口（大手町合同庁舎前・丸の内方面）",mapQuery:"大手町駅 C3b出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"丸ノ内線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","5号車3番扉"],details:"【単独乗降OK】全車いすスペース車両で目安値クリア。2号車3番扉・5号車3番扉が単独乗降の最適位置（2号車がEV近接）。"},
     {line:"東西線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"千代田線",canBoardIndependently:false,details:"目安値を満たさない乗降口が大半のため、必ず駅員の手配が必要。"},
     {line:"半蔵門線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"都営三田線",canBoardIndependently:true,nearElevatorCar:"3号車",safeDoors:["3号車3番扉"],details:"【単独乗降OK】3号車3番扉が単独乗降の最適位置。"},
   ]},
  {id:9,stationName:"六本木",smoothMetroUrl:"https://www.smoothmetro.jp/station/roppongi.html",
   surfaceElevator:{description:"3番出口（六本木ヒルズ方面）・1番出口にも地上EV",mapQuery:"六本木駅 3番出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"日比谷線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。地下深いためEV乗り継ぎあり。"},
     {line:"都営大江戸線",canBoardIndependently:true,nearElevatorCar:"4号車",safeDoors:["4号車2番扉"],details:"【単独乗降OK】4号車2番扉が単独乗降の最適位置。地下深いためEV乗り継ぎあり。"},
   ]},
  {id:10,stationName:"新宿三丁目",smoothMetroUrl:"https://www.smoothmetro.jp/station/shinjuku-sanchome.html",
   surfaceElevator:{description:"E5出口（新宿通り沿い・伊勢丹前）",mapQuery:"新宿三丁目駅 E5出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"丸ノ内線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","5号車3番扉"],details:"【単独乗降OK】全車いすスペース車両で目安値クリア。2号車3番扉・5号車3番扉が単独乗降の最適位置（2号車がEV近接）。"},
     {line:"副都心線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","9号車2番扉"],details:"【単独乗降OK】2号車3番扉・9号車2番扉が単独乗降の最適位置。2号車がEV近接。"},
     {line:"都営新宿線",canBoardIndependently:false,details:"ホームの一部で隙間・段差が目安値を超えるため係員確認を推奨。"},
   ]},
  {id:11,stationName:"千川",smoothMetroUrl:"https://www.smoothmetro.jp/station/senkawa.html",
   surfaceElevator:{description:"3番出口付近（千川駅前交差点北側）",mapQuery:"千川駅 3番出口 エレベーター"},
   hasWheelchairToilet:false,
   accessibilityByLine:[
     {line:"有楽町線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車4番扉","9号車1番扉"],details:"【単独乗降OK】2号車4番扉・9号車1番扉が単独乗降の最適位置。2号車がEV近接。"},
     {line:"副都心線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車3番扉","9号車2番扉"],details:"【単独乗降OK】2号車3番扉・9号車2番扉が単独乗降の最適位置。2号車がEV近接。"},
   ]},
  {id:12,stationName:"日本橋",smoothMetroUrl:"https://www.smoothmetro.jp/station/nihombashi.html",
   surfaceElevator:{description:"B12出口（日本橋三越前・中央通り沿い）",mapQuery:"日本橋駅 B12出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:true,nearElevatorCar:"6号車",safeDoors:["6号車1番扉","1号車3番扉"],details:"【単独乗降OK】6号車1番扉（および１号車3番扉）は、スロープなしで自力で乗降できる目安値をクリアしています。さらに6号車はホームのエレベーターの目の前に着くため移動が最短です。※もし混雑などで不安があり、駅員さんにスロープを依頼したい場合も、この『EVが目の前にある6号車』から声をかけるのが一番スムーズです。"},
     {line:"東西線",canBoardIndependently:false,details:"車いすスペース車両の一部で目安値未達。方面によって異なるため係員確認を推奨。"},
     {line:"都営浅草線",canBoardIndependently:true,nearElevatorCar:"4号車",safeDoors:["4号車2番扉"],details:"【単独乗降OK】4号車2番扉が単独乗降の最適位置。"},
   ]},
  {id:13,stationName:"月島",smoothMetroUrl:"https://www.smoothmetro.jp/station/tsukishima.html",
   surfaceElevator:{description:"1番出口（月島川沿い・もんじゃストリート方面）",mapQuery:"月島駅 1番出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"有楽町線",canBoardIndependently:true,nearElevatorCar:"2号車",safeDoors:["2号車4番扉","9号車1番扉"],details:"【単独乗降OK】2号車4番扉・9号車1番扉が単独乗降の最適位置。2号車がEV近接。"},
     {line:"都営大江戸線",canBoardIndependently:true,nearElevatorCar:"4号車",safeDoors:["4号車2番扉"],details:"【単独乗降OK】4号車2番扉が単独乗降の最適位置。"},
   ]},
  {id:14,stationName:"九段下",smoothMetroUrl:"https://www.smoothmetro.jp/station/kudanshita.html",
   surfaceElevator:{description:"1番出口（靖国神社方面・九段坂上）",mapQuery:"九段下駅 1番出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"東西線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"半蔵門線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
     {line:"都営新宿線",canBoardIndependently:false,details:"ホーム段差が目安値を超える箇所あり。係員確認を推奨。"},
   ]},
  {id:15,stationName:"溜池山王",smoothMetroUrl:"https://www.smoothmetro.jp/station/tameike-sanno.html",
   surfaceElevator:{description:"5番出口（溜池交差点・国道246号沿い）",mapQuery:"溜池山王駅 5番出口 エレベーター"},
   hasWheelchairToilet:true,
   accessibilityByLine:[
     {line:"銀座線",canBoardIndependently:true,nearElevatorCar:"6号車",safeDoors:["6号車1番扉","1号車3番扉"],details:"【単独乗降OK】6号車1番扉（および１号車3番扉）は、スロープなしで自力で乗降できる目安値をクリアしています。さらに6号車はホームのエレベーターの目の前に着くため移動が最短です。※もし混雑などで不安があり、駅員さんにスロープを依頼したい場合も、この『EVが目の前にある6号車』から声をかけるのが一番スムーズです。"},
     {line:"南北線",canBoardIndependently:false,details:"ホーム形状の理由から目安値未達のため、必ず駅員の手配が必要。"},
   ]},
];

